/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

import {
  devnetStrkClassHash,
  universalStrkAddress,
  sepoliaMainnetStrkClassHash,
  strkAbi,
  mainnetUSDCAddress,
  mainnetUSDTAddress,
  mainnetDAIAddress,
  mainnetETHAddress,
  mainnetStableClassHash,
  mainnetETHClassHash,
  MainnetStableAbi,
  ETHAbi
} from "../utils/Constants";

const preDeployedContracts = {
  devnet: {
    Strk: {
      address: universalStrkAddress,
      abi: strkAbi,
      classHash: devnetStrkClassHash,
    },
  },
  sepolia: {
    Strk: {
      address: universalStrkAddress,
      abi: strkAbi,
      classHash: sepoliaMainnetStrkClassHash,
    },
  },
  mainnet: {
    Strk: {
      address: universalStrkAddress,
      abi: strkAbi,
      classHash: sepoliaMainnetStrkClassHash,
    },
    USDC: {
      address: mainnetUSDCAddress,
      abi: MainnetStableAbi,
      classHash: mainnetStableClassHash,
    },
    USDT: {
      address: mainnetUSDTAddress,
      abi: MainnetStableAbi,
      classHash: mainnetStableClassHash,
    },
    DAI: {
      address: mainnetDAIAddress,
      abi: MainnetStableAbi,
      classHash: mainnetStableClassHash,
    },
    ETH: {
      address: mainnetETHAddress,
      abi: ETHAbi,
      classHash: mainnetETHClassHash,
    },
  },
} as const;

export default preDeployedContracts;
